POST http://localhost:3003/api/users
Content-Type: application/json

{
"username":"jovel",
"name":"yovel",
"password":"1243"
}
###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvdmVsIiwiaWQiOiI2NDMzMjEzNTZiMTUyMGFhNjFlNjFkM2QiLCJpYXQiOjE2ODEyMDkzOTl9.relL-OnSJihew41Cg1OYXX7Bmm7Mqbj2yaVqvi5I3Vs

{
    "title": "N12",
    "author": "Dani Kushmaru",
    "url": "mako.co.il",
   "likes": "15",
}
###
GET http://localhost:3003/api/users
###
GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username":"jovel",
    "password":"1243"
}
###